server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/medical-clinic
    username: postgres
    password: postgres
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.yml
  jackson:
    default-property-inclusion: NON_NULL
  mail:
    sender:
      host: ${MAIL_HOST:smtp.mail.ru}
      port: ${MAIL_PORT:465}
      username: ${MAIL_USERNAME:medical.clinic@bk.ru}
      password: ${MAIL_PASSWORD:Mypassword1}
      protocol: ${MAIL_PROTOCOL:smtps}
      topic: Your confirmation code
      text: To activate your account, please follow this link %s
app:
  security:
    jwtSecret: JDJhJDA4JGpUdXQ2eGdZTzE1RFpGU0lkMGpkYWVsZEtGdDhXSjh6YTRXbVptVjVVNjFCRkhXc0Q0em1X
    jwtTimeToLive: ${JWT_TIME_TO_LIVE:60}
    acticationCodeLength: ${ACTIVATION_CODE_LENGTH:6}
    confirmRegistrationAddress: http://localhost:8082/auth/register/confirm?token=