server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/medical-clinic
    username: postgres
    password: postgres
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.yml
  jackson:
    default-property-inclusion: NON_NULL
  mail:
    sender:
      host: ${MAIL_HOST:smtp.mail.ru}
      port: ${MAIL_PORT:465}
      username: ${MAIL_USERNAME:medical.clinic@bk.ru}
      password: ${MAIL_PASSWORD:Mypassword1}
      protocol: ${MAIL_PROTOCOL:smtps}
      registrationTopic: Your confirmation code
      restorationTopic: Password restoration
      registrationText: To activate your account, please enter this code %d
      restorationText: To restore your password, please enter this code %d
app:
  security:
    jwtSecret: JDJhJDA4JGpUdXQ2eGdZTzE1RFpGU0lkMGpkYWVsZEtGdDhXSjh6YTRXbVptVjVVNjFCRkhXc0Q0em1X
    jwtTimeToLive: ${JWT_TIME_TO_LIVE:60}
    acticationCodeLength: ${ACTIVATION_CODE_LENGTH:6}