server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/medical_clinic
    username: postgres
    password: postgres
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog.yml
  jackson:
    default-property-inclusion: NON_NULL
  mail:
    sender:
      host: ${MAIL_HOST:smtp.mail.ru}
      port: ${MAIL_PORT:465}
      username: ${MAIL_USERNAME:medical.clinic@bk.ru}
      password: ${MAIL_PASSWORD:Mypassword1}
      protocol: ${MAIL_PROTOCOL:smtps}
      registrationTopic: Your confirmation code
      registrationText: To activate your account, please follow <a href="%s">this link</a>
      registrationLink: http://localhost:8082/auth/register-finish?confirmationCode=%s
      restorationTopic: Password restoration
      restorationLink: http://localhost:8082/auth/restore-confirm?confirmationCode=%s
      restorationText: To restore your password, please enter this code %s
      htmlLayout: <!doctype html><html lang="en"><head><meta charset="utf-8"></head><body>%s</body></html>
  redirect:
    registration: http://localhost:9090/register-finish
    passwordRestoration: http://localhost:9090/restore-finish
app:
  security:
    jwtSecret: JDJhJDA4JGpUdXQ2eGdZTzE1RFpGU0lkMGpkYWVsZEtGdDhXSjh6YTRXbVptVjVVNjFCRkhXc0Q0em1X
    jwtTimeToLive: ${JWT_TIME_TO_LIVE:60}